function H = H_function(in1,in2)
%H_FUNCTION
%    H = H_FUNCTION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    25-Apr-2014 17:06:55

H = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[6, 6]);
